apiVersion: apps/v1
kind: Deployment
metadata:
  name: replica
  labels:
    app: motd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: motd
  template:
    metadata:
      labels:
        app: motd
    spec:
      containers:
      - name: motd
        image: soleilnoiir/hello:latest
        ports:
        - containerPort: 5000