apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  selector:
    app: motd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  clusterIP: 
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 